trigger:
  branches:
    include:
    - env/*
    - prod

pr: none

resources:
  repositories:
    - repository:  templates
      type: github
      name: StennGroup/stenn.pipeline-lib
      ref: refs/heads/master
      endpoint: StennGroup

extends:
  template: extendable/deploy-docker.yaml@templates
  parameters:
    DockerImages:
    - Img:
      ServiceName: 'structuring-notifications'
      DockerFilePath: 'src/StructuringNotifications.WebApp/Dockerfile'
      BuildContext: './src'
    ExecuteTests: Yes
    ProjectsToTest:
    - 'StructuringNotifications.sln'