trigger:
  paths: 
    include:
      - 'src/StructuringNotifications.Contracts'
  branches:
    include:
      - refs/heads/feature/*

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: StennGroup/stenn.pipeline-lib
      ref: refs/heads/master
      endpoint: StennGroup

extends:
  template: extendable/nuget-deploy.yaml@templates
  parameters:
    Directories:
    - dir:
      Directory: '$(Build.SourcesDirectory)/src/StructuringNotifications.Contracts'
      PackageName: 'StructuringNotifications.Contracts'
      ProjectFile: 'StructuringNotifications.Contracts.csproj'